version: '3.8'


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - ".:/app"

    environment:
      - CHOKIDAR_USEPOLLING=true

  express:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    command: "node server.js"
    ports:
      - "8080:8080"
    volumes:
      - "/app/node_modules"
      - ".:/app"
    depends_on:
      - web

  peerjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    command: >
               sh -c "npm install peer -g && peerjs --port 3001"

    ports:
      - "3001:3001"
    depends_on:
      - express
      - web

