version: '3'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "/app/node_modules"
      - ".:/app"

    environment:
      - CHOKIDAR_USEPOLLING=true

  express:
    build: .
    stdin_open: true
    tty: true
    command: node server.js
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - ".:/app"

  peerjs:
    build: .
    stdin_open: true
    tty: true
    command: >
               sh -c "npm install peer -g && peerjs --port 3001"

    ports:
      - "3001:3001"
    volumes:
      - "/app/node_modules"
      - ".:/app"

