version: '3'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile.ws
    stdin_open: true
    tty: true
    command: "node server.js"
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - ".:/app"

  peerjs:
    build:
      context: .
      dockerfile: Dockerfile.ws
    stdin_open: true
    tty: true
    command: >
      sh -c "npm install peer -g && peerjs --port 3001"

    ports:
      - "3001:3001"
    depends_on:
      - express
