FROM node:lts-alpine


# install simple http server for serving static content
RUN npm install -g http-server

RUN mkdir /app
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./
RUN npm  cache clear --force
RUN npm config set fetch-retry-mintimeout 20000
RUN npm config set fetch-retry-maxtimeout 120000

RUN npm install

COPY . .
EXPOSE 8080

CMD ["npm", "run", "serve"]